import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';

import { supabase } from '../utils/supabase';

export default function Home({ lessons }) {  
  return (
    <div className={styles.container}>
      <Head>
        <title>Supabase SaaS App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {lessons.map(lesson => (
          <p key={lesson.id}>{lesson.title}</p>
        ))}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getStaticProps = async () => {
  const { data: lessons } = await supabase.from('lesson').select('*');

  return {
    props: {
      lessons
    }
  }  
}